[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
dotenvy = "0.15.7"
simple_redis = "0.6.4"
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
